sudo: false
language: python

env:
  global:
    - TOXENV=py

jobs:
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial

    - language: python
      env:
        - TOXENV=style
      dist: xenial
      python: "3.7"

before_install:
  - pip install --quiet tox
  - tox --notest

script:
  - tox

notifications:
  email: false
