sudo: false
language: python

matrix:
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial

before_install:
  - pip install --quiet tox-travis
  - tox --notest

script:
  - tox

notifications:
  email: false
